---
deployment:
  tasks:
    # Show environment info in the deploy log (handy for debugging)
    - node -v || true
    - npm -v || true
    - pwd && ls -la

    # If npm is not found during deploy, uncomment this PATH line and redeploy:
    # - export PATH="/opt/alt/alt-nodejs18/root/usr/bin:/opt/cpanel/ea-nodejs18/bin:$PATH"

    # Optional: build-time key for your editor
    - export VITE_EDIT_KEY="edit"

    # Install & build
    - npm ci
    - npm run build

    # Publish to your site folder
    - export DEPLOYPATH="$HOME/public_html/ux"
    - mkdir -p "$DEPLOYPATH"
    - rsync -a --delete dist/ "$DEPLOYPATH"/

    # SPA fallback (first time only)
    - if [ ! -f "$DEPLOYPATH/.htaccess" ]; then
        printf "%s\n" "RewriteEngine On" "RewriteBase /ux/" "RewriteRule ^index\\.html$ - [L]" "RewriteCond %{REQUEST_FILENAME} !-f" "RewriteCond %{REQUEST_FILENAME} !-d" "RewriteRule . /ux/index.html [L]" > "$DEPLOYPATH/.htaccess";
      fi
